version: "3.0"

services:
  mongodb:
    container_name: mongodb
    image: mongo:5.0
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    networks:
      - nest_network

  zookeeper:
    container_name: zookeeper
    image: bitnami/zookeeper
    restart: always
    ports:
      - 2181:2181
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - nest_network

  kafka:
    container_name: kafka
    image: bitnami/kafka
    ports:
      - 9092:9092
      - 29092:29092
    restart: always
    volumes:
      - kafka_data:/bitnami
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
    depends_on:
      - zookeeper
    networks:
      - nest_network

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  mongodb_data:
    driver: local

networks:
  nest_network:
    name: nest_network
    driver: bridge